# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Anshul Malik
tagline:          'H4cK3r'
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /CTFs/

author:
  name:           'Anshul'
  url:            https://anshulmalik.github.io/me

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/AnshulMalik/CTFs

plugins:
  - jekyll-paginate